name: Gradle Build & Codecov

on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Fix gradlew permission
        run: chmod +x ./gradlew

      - name: Build using Gradle Wrapper
        run: ./gradlew build

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3